/**
 * mods/graphify/route.mjs
 *
 * graphify mod — provides the dashboard's Graph functionality entirely
 * through the mod system. No graph-specific code lives in BizarHarness
 * itself. After installing this mod, the user sees:
 *
 *   - `Graph` view card in the Mods tab (via web/index.html below)
 *   - API endpoints at /api/mods/graphify/*
 *
 * Endpoints:
 *   GET    /status                 graph exists + counts
 *   GET    /html                   serve graph.html
 *   GET    /report                 serve GRAPH_REPORT.md
 *   POST   /build                  kick off async build
 *   GET    /build/:jobId/status    poll build progress
 *   GET    /health                 mod liveness probe
 *
 * The build pipeline (formerly `bizar graph build`):
 *   1. Detect any LLM API key in env. If none, write a code-only
 *      `.graphifyignore` so graphify runs offline.
 *   2. Run `graphify .` in the project root with GRAPHIFY_OUT set to
 *      `.bizar/graph/`.
 *   3. If graphify exits non-zero AND no LLM key is set, fall back to
 *      reconstructing graph.json from the AST cache.
 *   4. Run `graphify cluster-only` to produce graph.html + GRAPH_REPORT.md.
 *   5. Hoist outputs from `./graphify-out/` to canonical `.bizar/graph/`
 *      paths the mod serves.
 *
 * Permissions required:
 *   - fs:read:.bizar/graph
 *   - fs:write:.bizar/graph          (graph.json, graph.html, GRAPH_REPORT.md)
 *   - fs:write:.graphifyignore       (auto-generated code-only filter)
 *   - process:spawn:graphify         (the Python CLI)
 *   - process:spawn:python3          (fallback for pip/pipx installs)
 *   - process:spawn:which            (binary resolution)
 */
import fs from 'node:fs';
import path from 'node:path';
import os from 'node:os';
import crypto from 'node:crypto';
import { spawn, spawnSync } from 'node:child_process';

const GRAPH_DIR_NAME = '.bizar/graph';
const GRAPHIFY_OUT_ENV = 'GRAPHIFY_OUT';

// LLM key env vars graphify recognises for semantic extraction of
// docs/papers/images. If NONE are set, graphify refuses to run on a
// corpus containing any non-code file. We auto-detect this case and
// write a code-only .graphifyignore so a fresh checkout can build
// the graph offline with no LLM key.
const GRAPHIFY_LLM_KEY_ENVS = [
  'GEMINI_API_KEY', 'GOOGLE_API_KEY',
  'MOONSHOT_API_KEY',
  'ANTHROPIC_API_KEY',
  'OPENAI_API_KEY',
  'DEEPSEEK_API_KEY',
  'AZURE_OPENAI_API_KEY',
];

// Minimal .graphifyignore that restricts graphify to code-only extraction.
// Written automatically by the build when no LLM key is set. The user can
// override this file with their own .graphifyignore — we never overwrite
// a pre-existing one.
const CODE_ONLY_GRAPHIFYIGNORE = [
  '# Auto-generated by the graphify mod (no LLM API key detected).',
  '# Code-only mode: restricts extraction to source files (processed locally',
  "# via tree-sitter — no API key needed). Delete this file and re-run once",
  '# you\'ve set one of: GEMINI_API_KEY, GOOGLE_API_KEY, MOONSHOT_API_KEY,',
  '# ANTHROPIC_API_KEY, OPENAI_API_KEY, DEEPSEEK_API_KEY, AZURE_OPENAI_API_KEY.',
  '',
  '# Heavy / vendored dirs to skip entirely',
  'node_modules/',
  '.git/',
  '.bizar/',
  '.agents/',
  'dist/',
  'build/',
  'coverage/',
  '',
  '# Agent system prompts — Markdown with YAML frontmatter, not project docs.',
  'config/agents/',
  '',
  '# Non-code file types — graphify would need an LLM for these',
  '*.md',
  '*.markdown',
  '*.rst',
  '*.txt',
  '*.pdf',
  '*.docx',
  '*.html',
  '*.htm',
  '',
  '# Image / binary assets',
  '*.png',
  '*.jpg',
  '*.jpeg',
  '*.gif',
  '*.svg',
  '*.webp',
  '*.ico',
  '*.mp4',
  '*.mp3',
  '*.wav',
  '*.pdf',
];

// ── Active build jobs (in-memory) ───────────────────────────────────────
const buildJobs = new Map();

// ── Project resolution ──────────────────────────────────────────────────
function resolveActiveProjectRoot() {
  try {
    const active = globalThis.__bizarProjectsStore?.active?.();
    if (active && active.path && fs.existsSync(active.path)) return active.path;
  } catch { /* ignore */ }
  return process.cwd();
}

function resolveGraphDir() {
  return path.resolve(resolveActiveProjectRoot(), GRAPH_DIR_NAME);
}

// ── Status readers ──────────────────────────────────────────────────────
function readGraphStats(graphJsonPath) {
  if (!fs.existsSync(graphJsonPath)) return null;
  try {
    const graph = JSON.parse(fs.readFileSync(graphJsonPath, 'utf8'));
    const nodes = Array.isArray(graph.nodes) ? graph.nodes : [];
    const links = Array.isArray(graph.links) ? graph.links : [];
    const communities = new Set();
    for (const n of nodes) {
      if (n.community !== undefined && n.community !== null) communities.add(n.community);
    }
    const st = fs.statSync(graphJsonPath);
    return {
      exists: true,
      nodes: nodes.length,
      edges: links.length,
      communities: communities.size,
      lastBuilt: st.mtime.toISOString(),
      sizeBytes: st.size,
    };
  } catch {
    return null;
  }
}

function hasLlmKey() {
  return GRAPHIFY_LLM_KEY_ENVS.some((k) => {
    const v = process.env[k];
    return typeof v === 'string' && v.length > 0;
  });
}

// ── Cache-fallback reconstruction ───────────────────────────────────────
// graphify's pipeline has two stages: AST extraction (local tree-sitter,
// always runs) and semantic extraction (LLM, optional). If the LLM step
// aborts but the AST cache is intact, reconstruct graph.json from it.
function buildGraphFromCache(graphDir) {
  const cacheAstRoot = path.join(graphDir, 'cache', 'ast');
  if (!fs.existsSync(cacheAstRoot)) {
    throw new Error(`No AST cache found at ${cacheAstRoot}. Run a full build first to populate it.`);
  }
  const entries = fs.readdirSync(cacheAstRoot);
  if (entries.length === 0) {
    throw new Error(`AST cache directory ${cacheAstRoot} is empty.`);
  }
  // graphify uses one version directory like v0.8.46. Pick the first.
  const cacheDir = path.join(cacheAstRoot, entries[0]);
  const files = fs.readdirSync(cacheDir).filter((f) => f.endsWith('.json'));

  const nodesById = new Map();
  const edges = [];
  for (const f of files) {
    const raw = JSON.parse(fs.readFileSync(path.join(cacheDir, f), 'utf8'));
    for (const n of raw.nodes || []) {
      if (!nodesById.has(n.id)) nodesById.set(n.id, n);
    }
    for (const e of raw.edges || []) edges.push(e);
  }
  const nodes = Array.from(nodesById.values());
  return {
    directed: false,
    multigraph: false,
    graph: {},
    nodes,
    links: edges,
  };
}

// ── Output hoisting ─────────────────────────────────────────────────────
// cluster-only writes its outputs to a nested graphify-out/ directory.
// This hoists them up to the canonical paths the mod serves.
function promoteFromDir(srcDir, dstDir) {
  for (const name of ['graph.html', 'GRAPH_REPORT.md', 'graph.json']) {
    const src = path.join(srcDir, name);
    const dst = path.join(dstDir, name);
    if (fs.existsSync(src)) {
      try { fs.copyFileSync(src, dst); } catch { /* ignore */ }
    }
  }
}

// ── Build pipeline ──────────────────────────────────────────────────────
async function runBuild(projectRoot, broadcast, jobId) {
  const graphDir = path.resolve(projectRoot, GRAPH_DIR_NAME);
  fs.mkdirSync(graphDir, { recursive: true });
  const log = (msg) => broadcast({ type: 'graphify:build:log', jobId, line: msg });

  const llmKeyPresent = hasLlmKey();
  log(`[preflight] LLM key present: ${llmKeyPresent}`);

  // Step 1: code-only fallback ignore file
  if (!llmKeyPresent) {
    const ignorePath = path.join(projectRoot, '.graphifyignore');
    if (!fs.existsSync(ignorePath)) {
      fs.writeFileSync(ignorePath, CODE_ONLY_GRAPHIFYIGNORE.join('\n') + '\n', 'utf8');
      log('[preflight] No LLM key — wrote code-only .graphifyignore');
    } else {
      log('[preflight] No LLM key — using existing .graphifyignore');
    }
  }

  // Step 2: graphify extract
  log('[build] Running graphify extract...');
  const extractArgs = ['.'];
  let code = runGraphify(['extract', ...extractArgs], projectRoot, graphDir);

  // Step 3: offline cache fallback
  if (code !== 0 && !llmKeyPresent) {
    const cacheAstRoot = path.join(graphDir, 'cache', 'ast');
    let cachePopulated = false;
    try {
      const entries = fs.readdirSync(cacheAstRoot, { withFileTypes: true });
      for (const e of entries) {
        if (!e.isDirectory()) continue;
        const files = fs.readdirSync(path.join(cacheAstRoot, e.name));
        if (files.some((f) => f.endsWith('.json'))) {
          cachePopulated = true;
          break;
        }
      }
    } catch { /* ignore */ }

    if (!cachePopulated) {
      log('[fallback] No AST cache — populating with dummy-key graphify run');
      // Run graphify with a dummy key to populate the AST cache; semantic
      // step will fail but the per-file JSON we need is written.
      runGraphify(['.'], projectRoot, graphDir, {
        ANTHROPIC_API_KEY: 'sk-bizar-graph-dummy',
      });
    }

    // Reconstruct graph.json from cache
    log('[fallback] Reconstructing graph.json from AST cache');
    try {
      const graph = buildGraphFromCache(graphDir);
      const graphJsonPath = path.join(graphDir, 'graph.json');
      fs.writeFileSync(graphJsonPath, JSON.stringify(graph, null, 2), 'utf8');
      // Match graphify's secondary output shape so cluster-only can find it.
      fs.writeFileSync(
        path.join(graphDir, '.graphify_analysis.json'),
        JSON.stringify({ schema_version: 1, generated_at: new Date().toISOString(), clusters: [] }, null, 2),
        'utf8',
      );
      log(`[fallback] ✓ ${graph.nodes.length} nodes, ${graph.links.length} edges`);
      code = 0;
    } catch (err) {
      log(`[fallback] ✗ ${err.message}`);
      code = 1;
    }
  }

  if (code === 0) {
    // Step 4: cluster-only for graph.html + GRAPH_REPORT.md
    const graphJson = path.join(graphDir, 'graph.json');
    if (fs.existsSync(graphJson)) {
      log('[cluster] Running cluster-only to generate graph.html + GRAPH_REPORT.md');
      const clusterCode = runGraphify(
        ['cluster-only', '.', '--graph', graphJson],
        projectRoot,
        graphDir,
      );
      if (clusterCode !== 0) {
        log(`[cluster] ⚠ cluster-only returned ${clusterCode} — graph.json built but graph.html may be stale`);
      } else {
        // Hoist outputs up to canonical paths
        const out = path.join(graphDir, 'graphify-out');
        if (!fs.existsSync(out)) {
          const cwdOut = path.join(projectRoot, 'graphify-out');
          if (fs.existsSync(cwdOut)) promoteFromDir(cwdOut, graphDir);
        } else {
          promoteFromDir(out, graphDir);
        }
        log('[cluster] ✓ graph.html + GRAPH_REPORT.md ready');
      }
    }
  }

  return code;
}

/**
 * Resolve and invoke the graphify CLI. Tries the bare `graphify` binary
 * first (the uv-tool shim lives on PATH), falls back to `python3 -m graphify`
 * for pip/pipx installs.
 */
function runGraphify(subArgs, cwd, graphDir, extraEnv = {}) {
  const env = {
    ...process.env,
    [GRAPHIFY_OUT_ENV]: graphDir,
    ...extraEnv,
  };
  const whichCmd = process.platform === 'win32' ? 'where' : 'which';
  let bin = null;
  try {
    const r = spawnSync(whichCmd, ['graphify'], { encoding: 'utf8', timeout: 5000 });
    if (r.status === 0 && (r.stdout || '').trim().length > 0) bin = 'graphify';
  } catch { /* fall through */ }

  if (bin) {
    const result = spawnSync(bin, subArgs, { stdio: 'inherit', env, timeout: 0, cwd });
    return result.status ?? 1;
  }
  const py = process.platform === 'win32' ? 'python' : 'python3';
  const result = spawnSync(py, ['-m', 'graphify', ...subArgs], { stdio: 'inherit', env, timeout: 0, cwd });
  return result.status ?? 1;
}

// ── Mod router registration ─────────────────────────────────────────────
export default function register({ router, broadcast = () => {} }) {
  // GET /status
  router.get('/status', (req, res) => {
    const graphDir = resolveGraphDir();
    const graphJsonPath = path.join(graphDir, 'graph.json');
    const htmlPath = path.join(graphDir, 'graph.html');
    const reportPath = path.join(graphDir, 'GRAPH_REPORT.md');
    const stats = readGraphStats(graphJsonPath);
    const out = { exists: stats !== null, graphDir: graphDir.replace(os.homedir(), '~') };
    if (stats) {
      out.nodes = stats.nodes;
      out.edges = stats.edges;
      out.communities = stats.communities;
      out.lastBuilt = stats.lastBuilt;
      out.sizeBytes = stats.sizeBytes;
      out.hasHtml = fs.existsSync(htmlPath);
      out.hasReport = fs.existsSync(reportPath);
    }
    const jobs = [];
    for (const [id, job] of buildJobs.entries()) {
      jobs.push({ id, status: job.status, startedAt: job.startedAt, finishedAt: job.finishedAt, exitCode: job.exitCode });
    }
    out.buildJobs = jobs;
    out.llmKeyPresent = hasLlmKey();
    res.json(out);
  });

  // GET /html
  router.get('/html', (req, res) => {
    const htmlPath = path.join(resolveGraphDir(), 'graph.html');
    if (!fs.existsSync(htmlPath)) {
      res.status(404).json({ error: 'not_built', message: 'graph.html not found. Run a build first.' });
      return;
    }
    res.set('Content-Type', 'text/html; charset=utf-8');
    res.set('Cache-Control', 'no-cache');
    res.send(fs.readFileSync(htmlPath, 'utf8'));
  });

  // GET /report
  router.get('/report', (req, res) => {
    const reportPath = path.join(resolveGraphDir(), 'GRAPH_REPORT.md');
    if (!fs.existsSync(reportPath)) {
      res.status(404).json({ error: 'not_built', message: 'GRAPH_REPORT.md not found.' });
      return;
    }
    res.set('Content-Type', 'text/markdown; charset=utf-8');
    res.send(fs.readFileSync(reportPath, 'utf8'));
  });

  // POST /build — kick off async build
  router.post('/build', (req, res) => {
    const jobId = crypto.randomUUID().slice(0, 8);
    const startedAt = new Date().toISOString();
    const projectRoot = resolveActiveProjectRoot();

    const logDir = path.join(os.homedir(), '.cache', 'bizar', 'graph-logs');
    fs.mkdirSync(logDir, { recursive: true });
    const logPath = path.join(logDir, `graph-build-${jobId}.log`);
    fs.writeFileSync(logPath, `\n[${startedAt}] graphify mod build (job=${jobId})\n`);

    buildJobs.set(jobId, {
      id: jobId, status: 'running', startedAt, finishedAt: null, exitCode: null, logPath,
    });

    // Run build in-process (not detached) so we can stream via broadcast.
    // For typical repos the build takes < 60s.
    runBuild(projectRoot, (event) => {
      try {
        fs.appendFileSync(logPath, `[${new Date().toISOString()}] ${event.line || JSON.stringify(event)}\n`);
      } catch { /* ignore */ }
      broadcast(event);
    }, jobId)
      .then((code) => {
        const finishedAt = new Date().toISOString();
        const job = buildJobs.get(jobId);
        if (!job) return;
        job.finishedAt = finishedAt;
        job.exitCode = code;
        job.status = code === 0 ? 'done' : 'failed';
        broadcast({ type: 'graphify:build:done', jobId, status: job.status, exitCode: code });
        setTimeout(() => buildJobs.delete(jobId), 60 * 60 * 1000);
      })
      .catch((err) => {
        const job = buildJobs.get(jobId);
        if (job) {
          job.status = 'failed';
          job.error = err.message;
          job.finishedAt = new Date().toISOString();
          broadcast({ type: 'graphify:build:done', jobId, status: 'failed', error: err.message });
        }
      });

    res.json({ ok: true, jobId, startedAt, logPath, message: 'Build started. Poll /api/mods/graphify/build/:jobId/status for completion.' });
  });

  // GET /build/:jobId/status
  router.get('/build/:jobId/status', (req, res) => {
    const { jobId } = req.params;
    const job = buildJobs.get(jobId);
    if (!job) {
      res.status(404).json({ error: 'unknown_job', message: `No build job with id ${jobId}.` });
      return;
    }
    res.json({
      id: job.id, status: job.status, startedAt: job.startedAt,
      finishedAt: job.finishedAt, exitCode: job.exitCode, logPath: job.logPath,
    });
  });

  // GET /health
  router.get('/health', (req, res) => {
    res.json({ ok: true, mod: 'graphify', version: '1.1.0' });
  });
}
