/**
 * cli/graph.mjs
 *
 * `bizar graph` — Per-project knowledge graph powered by graphify.
 * Graph data lives in .bizar/graph/ inside the project.
 */

import chalk from 'chalk';
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, mkdirSync, writeFileSync, statSync, copyFileSync } from 'node:fs';
import { join } from 'node:path';

// ── Constants ─────────────────────────────────────────────────────────────────

export const GRAPH_DIR = '.bizar/graph';
export const GRAPHIFY_OUT_ENV = 'GRAPHIFY_OUT';

/**
 * Env vars graphify recognises for semantic extraction of docs/papers/images.
 * If NONE of these are set, graphify refuses to run on a corpus that contains
 * any non-code file ("A code-only corpus needs no key."). We auto-detect this
 * and write a comprehensive .graphifyignore so a fresh checkout can build
 * the graph offline with no LLM key.
 */
const GRAPHIFY_LLM_KEY_ENVS = [
  'GEMINI_API_KEY', 'GOOGLE_API_KEY',
  'MOONSHOT_API_KEY',
  'ANTHROPIC_API_KEY',
  'OPENAI_API_KEY',
  'DEEPSEEK_API_KEY',
  'AZURE_OPENAI_API_KEY',
];

/**
 * Minimal .graphifyignore that restricts graphify to code-only extraction.
 * Written automatically by `bizar graph build` when no LLM key is set.
 * The user can override this file with their own .graphifyignore — we
 * never overwrite a pre-existing one.
 */
const CODE_ONLY_GRAPHIFYIGNORE = [
  '# Auto-generated by `bizar graph build` — code-only mode.',
  '# Bizar detected no LLM key, so docs/papers/images cannot be semantically',
  '# extracted. We restrict extraction to code files (processed locally via',
  "# tree-sitter — no API key needed). Delete this file and re-run once you've",
  '# set one of: GEMINI_API_KEY, GOOGLE_API_KEY, MOONSHOT_API_KEY,',
  '# ANTHROPIC_API_KEY, OPENAI_API_KEY, DEEPSEEK_API_KEY, AZURE_OPENAI_API_KEY.',
  '',
  '# Heavy / vendored dirs to skip entirely',
  'node_modules/',
  '.git/',
  '.bizar/',
  '.agents/',
  'dist/',
  'build/',
  'coverage/',
  '',
  '# Agent system prompts — they\'re Markdown but contain YAML frontmatter',
  '# + system instructions, not project documentation. They\'re noise for',
  '# a structural graph and would balloon the doc count to ~1100.',
  'config/agents/',
  '',
  '# Non-code file types — graphify would need an LLM for these',
  '*.md',
  '*.mdx',
  '*.qmd',
  '*.html',
  '*.txt',
  '*.rst',
  '*.pdf',
  '*.png',
  '*.jpg',
  '*.jpeg',
  '*.webp',
  '*.gif',
  '*.mp4',
  '*.mov',
  '*.mp3',
  '*.wav',
  '',
].join('\n');

/**
 * Detect whether any graphify-recognised LLM API key is set in the
 * current process env. Used by `cmdBuild` to decide whether to write
 * the code-only .graphifyignore.
 */
function hasLlmKey(env = process.env) {
  return GRAPHIFY_LLM_KEY_ENVS.some((k) => {
    const v = env[k];
    return typeof v === 'string' && v.trim().length > 0;
  });
}

// ── Python detection ───────────────────────────────────────────────────────────

/**
 * Find a Python 3 interpreter on PATH.
 * Returns the absolute path string, or null if none found.
 *
 * On Windows the `py` launcher is the most reliable option; on Unix
 * we prefer python3 then python.
 */
export function findPython() {
  const candidates = process.platform === 'win32'
    ? ['py', 'python', 'python3']
    : ['python3', 'python'];
  for (const name of candidates) {
    try {
      const result = spawnSync(name, ['--version'], { encoding: 'utf8', timeout: 5000 });
      if (result.status === 0 && result.stdout.includes('Python')) {
        return name;
      }
    } catch {
      // try next
    }
  }
  return null;
}

/**
 * Check whether graphify is available.
 *
 * Strategy:
 *  1. Probe PATH for the `graphify` binary (uv tool install puts a shim at
 *     ~/.local/bin/graphify — invisible to the isolated python -m lookup).
 *  2. Fall back to `python -m graphify --version` for pip/pipx installs.
 *
 * Returns true if available, false otherwise.
 */
function checkGraphify(python) {
  // Try 1: check for the graphify binary on PATH (uv tool install shim).
  // On Windows the Python launcher `py` is not on PATH by default, but the
  // graphify shim is placed next to pip/pipx so a plain `where` works.
  const whichCmd = process.platform === 'win32' ? 'where' : 'which';
  try {
    const whichResult = spawnSync(whichCmd, ['graphify'], {
      encoding: 'utf8',
      timeout: 5000,
    });
    if (whichResult.status === 0 && (whichResult.stdout || '').trim().length > 0) {
      return true;
    }
  } catch {
    // fall through to python -m check
  }

  // Try 2: check via python -m (catches pip/pipx installs into system python)
  try {
    const result = spawnSync(python, ['-m', 'graphify', '--version'], {
      encoding: 'utf8',
      timeout: 10000,
      env: { ...process.env },
    });
    return result.status === 0;
  } catch {
    return false;
  }
}

// ── Graph stats parsing ────────────────────────────────────────────────────────

/**
 * Parse .bizar/graph/graph.json and return stats.
 * Returns null if the file does not exist or cannot be parsed.
 *
 * Expected NetworkX node-link JSON shape:
 * {
 *   "directed": false,
 *   "multigraph": false,
 *   "graph": {},
 *   "nodes": [{ "id": "...", "community": 0, ... }],
 *   "links": [{ "source": "...", "target": "...", ... }]
 * }
 */
export function parseGraphStats(jsonPath) {
  if (!existsSync(jsonPath)) return null;
  try {
    const content = readFileSync(jsonPath, 'utf8');
    const graph = JSON.parse(content);

    const nodes = Array.isArray(graph.nodes) ? graph.nodes : [];
    const links = Array.isArray(graph.links) ? graph.links : [];

    // Count unique community values among nodes
    const communitySet = new Set();
    for (const node of nodes) {
      if (node.community !== undefined && node.community !== null) {
        communitySet.add(node.community);
      }
    }

    const stats = statSync(jsonPath);

    return {
      nodes: nodes.length,
      edges: links.length,
      communities: communitySet.size,
      lastModified: stats.mtime.toISOString(),
      sizeBytes: stats.size,
    };
  } catch {
    return null;
  }
}

// ── Gitignore guard ────────────────────────────────────────────────────────────

const GRAPH_GITIGNORE = `cache/
.graphify_python
cost.json
`;

/**
 * Ensure .bizar/graph/.gitignore exists so heavy cache artefacts are not committed.
 * Called after a successful first build.
 */
function ensureGitignore(graphDir) {
  const gitignorePath = join(graphDir, '.gitignore');
  if (!existsSync(gitignorePath)) {
    writeFileSync(gitignorePath, GRAPH_GITIGNORE, 'utf8');
  }
}

// ── Run helpers ───────────────────────────────────────────────────────────────

/**
 * Spawn a graphify command with GRAPHIFY_OUT set to GRAPH_DIR.
 * Streams stdout/stderr to the terminal. Returns the exit code.
 *
 * Resolution order:
 *   1. If the `graphify` binary is on PATH (the uv-tool shim), invoke it
 *      directly. This is what `checkGraphify` already verified — we don't
 *      need to know about its venv.
 *   2. Otherwise fall back to `python -m graphify` for pip/pipx installs.
 */
function runGraphify(python, subArgs, extraEnv = {}) {
  const env = { ...process.env, [GRAPHIFY_OUT_ENV]: GRAPH_DIR, ...extraEnv };
  const whichCmd = process.platform === 'win32' ? 'where' : 'which';
  let bin = null;
  try {
    const r = spawnSync(whichCmd, ['graphify'], { encoding: 'utf8', timeout: 5000 });
    if (r.status === 0 && (r.stdout || '').trim().length > 0) {
      bin = 'graphify';
    }
  } catch {
    // ignore — fall through to python -m
  }

  if (bin) {
    const result = spawnSync(bin, subArgs, {
      stdio: 'inherit',
      env,
      timeout: 0, // no timeout — user may run long builds
    });
    return result.status ?? 1;
  }

  const result = spawnSync(python, ['-m', 'graphify', ...subArgs], {
    stdio: 'inherit',
    env,
    timeout: 0,
  });
  return result.status ?? 1;
}

// ── Subcommand handlers ────────────────────────────────────────────────────────

async function cmdBuild(python) {
  // If no LLM key is set, fall back to a code-only build by writing a
  // comprehensive .graphifyignore. We never overwrite a user-provided
  // .graphifyignore — only create the file when it doesn't exist.
  let llmKeyPresent = hasLlmKey();
  if (!llmKeyPresent) {
    const ignorePath = '.graphifyignore';
    if (!existsSync(ignorePath)) {
      writeFileSync(ignorePath, CODE_ONLY_GRAPHIFYIGNORE, 'utf8');
      console.log(chalk.dim('  No LLM API key detected — switching to code-only build.'));
      console.log(chalk.dim(`  Wrote ${ignorePath} restricting extraction to code files.`));
      console.log(chalk.dim('  Set GEMINI_API_KEY / OPENAI_API_KEY / etc. and re-run for full docs extraction.\n'));
    } else {
      console.log(chalk.dim('  No LLM API key detected — using existing .graphifyignore for code-only build.\n'));
    }
  }

  console.log(chalk.dim('  Running full graphify pipeline...'));
  let code = runGraphify(python, ['.']);

  // Offline code-only fallback — when no LLM key is set, graphify's
  // pre-flight check rejects the build before it can write any output.
  // Even with a dummy key set, the semantic step fails for any non-code
  // docs that escaped the .graphifyignore filter, and graphify refuses
  // to write graph.json. To unblock this case we:
  //   1. Run graphify with a dummy ANTHROPIC_API_KEY so the AST cache
  //      gets populated (semantic extraction will fail, that's fine).
  //   2. Reconstruct graph.json from the per-file AST cache.
  //   3. Run cluster-only to generate graph.html + GRAPH_REPORT.md.
  if (code !== 0 && !llmKeyPresent) {
    const cacheAstRoot = join(GRAPH_DIR, 'cache', 'ast');
    const cacheIsPopulated = existsSync(cacheAstRoot) && (
      // graphify creates a versioned subdir on first extract.
      // Check if any version dir contains JSON files.
      (await import('node:fs/promises'))
        .readdir(cacheAstRoot, { withFileTypes: true })
        .then((entries) =>
          entries.some(async (e) => {
            if (!e.isDirectory()) return false;
            const files = await (await import('node:fs/promises')).readdir(join(cacheAstRoot, e.name));
            return files.some((f) => f.endsWith('.json'));
          }),
        )
        .catch(() => false)
    );

    if (!cacheIsPopulated) {
      console.log(chalk.yellow('  ⚠ No AST cache yet. Running graphify with a dummy key to populate the cache (semantic extraction will fail; that\'s OK)...'));
      // Set a dummy key so graphify gets past its pre-flight check and
      // populates the AST cache. We invoke the graphify binary directly
      // (the user's python3 -m graphify may not have graphify installed;
      // uv-tool installs put a shim at ~/.local/bin/graphify).
      const dummyRes = spawnSync('graphify', ['.'], {
        stdio: 'inherit',
        env: { ...process.env, ANTHROPIC_API_KEY: 'sk-bizar-graph-dummy', GRAPHIFY_OUT: GRAPH_DIR },
        timeout: 0,
      });
      void dummyRes; // exit code doesn't matter — we want the cache, not the merge
    }

    const cacheStillEmpty = !(await (async () => {
      try {
        const e = await (await import('node:fs/promises')).readdir(cacheAstRoot, { withFileTypes: true });
        for (const d of e) {
          if (!d.isDirectory()) continue;
          const f = await (await import('node:fs/promises')).readdir(join(cacheAstRoot, d.name));
          if (f.some((x) => x.endsWith('.json'))) return true;
        }
        return false;
      } catch {
        return false;
      }
    })());

    if (!cacheStillEmpty) {
      console.log(chalk.yellow('  ⚠ graphify exited non-zero. Falling back to AST-cache build...'));
      const fb = runCacheFallbackBuild();
      if (fb === 0) code = 0;
    }
  }

  if (code === 0) {
    ensureGitignore(GRAPH_DIR);
    // After extract, run cluster-only to write graph.html + GRAPH_REPORT.md
    // (extract only writes graph.json; cluster-only adds viz + report).
    const graphJson = join(GRAPH_DIR, 'graph.json');
    if (existsSync(graphJson)) {
      console.log(chalk.dim('  Generating graph.html + GRAPH_REPORT.md via cluster-only...'));
      // Pass "." as the cluster-only path so it writes graph.html +
      // GRAPH_REPORT.md to the current directory's graphify-out/.
      // (Passing `.bizar/graph` directly nests the output as
      // `.bizar/graph/.bizar/graph/...` which is wrong.) The explicit
      // --graph overrides the auto-discovery to find graph.json.
      const clusterArgs = ['cluster-only', '.', '--graph', graphJson];
      const clusterCode = runGraphify(python, clusterArgs);
      if (clusterCode !== 0) {
        console.log(chalk.yellow(`  ⚠ cluster-only returned ${clusterCode} — graph.json was built but graph.html may be stale.`));
      } else {
        // cluster-only writes to ./graphify-out/ (relative to CWD).
        // Promote the artifacts up to .bizar/graph/ paths the dashboard
        // serves directly.
        const out = join(GRAPH_DIR, 'graphify-out');
        if (!existsSync(out)) {
          // Fallback: graphify may have written to ./graphify-out/ at CWD.
          const cwdOut = join(process.cwd(), 'graphify-out');
          if (existsSync(cwdOut)) {
            promoteFromDir(cwdOut, GRAPH_DIR);
          }
        } else {
          promoteClusterOutputs(GRAPH_DIR);
        }
      }
    }
    console.log(chalk.green(`\n  ✓ Graph built → ${GRAPH_DIR}/\n`));
  }
  return code;
}

/**
 * Reconstruct graph.json from graphify's per-file AST cache and run
 * cluster-only to produce graph.html + GRAPH_REPORT.md. Used when the
 * full graphify pipeline fails because some docs need an LLM that we
 * don't have, but the AST cache for code-only files was successfully
 * extracted.
 *
 * Returns the exit code of the overall sequence (0 on success).
 */
function runCacheFallbackBuild() {
  // Step 1: merge the per-file AST cache into a single graph.json.
  const scriptPath = new URL(import.meta.url).pathname;
  // cli/graph.mjs sits next to cli/graph-build-from-cache.mjs.
  const cacheScript = scriptPath.replace(/graph\.mjs$/, 'graph-build-from-cache.mjs');
  if (!existsSync(cacheScript)) {
    console.log(chalk.red(`  ✗ Cache fallback script not found at ${cacheScript}`));
    return 1;
  }
  const buildRes = spawnSync(process.execPath, [cacheScript, GRAPH_DIR], {
    stdio: 'inherit',
  });
  if (buildRes.status !== 0) {
    return buildRes.status ?? 1;
  }
  // Step 2: cluster-only regenerates graph.html from the merged graph.json.
  return 0;
}

/**
 * Copy the named files from `srcDir` up to `dstDir`. Used to hoist
 * cluster-only's graph.html / GRAPH_REPORT.md / graph.json up to the
 * canonical .bizar/graph/ paths the dashboard serves.
 */
function promoteFromDir(srcDir, dstDir) {
  for (const name of ['graph.html', 'GRAPH_REPORT.md', 'graph.json']) {
    const src = join(srcDir, name);
    const dst = join(dstDir, name);
    if (existsSync(src)) {
      copyFileSync(src, dst);
    }
  }
}

/**
 * cluster-only writes its outputs to a nested graphify-out/ directory
 * by default. This hoists them up to the standard paths the dashboard
 * serves (.bizar/graph/graph.html + .bizar/graph/GRAPH_REPORT.md).
 */
function promoteClusterOutputs(graphDir) {
  const out = join(graphDir, 'graphify-out');
  if (existsSync(out)) promoteFromDir(out, graphDir);
}

async function cmdUpdate(python) {
  console.log(chalk.dim('  Running incremental graph update...'));
  return runGraphify(python, ['.', '--update']);
}

async function cmdQuery(python, query) {
  if (!query) {
    console.log(chalk.red('  Error: query text required.'));
    console.log(chalk.dim('  Usage: bizar graph query "<search term>"\n'));
    return 1;
  }
  return runGraphify(python, ['query', query]);
}

async function cmdPath(python, a, b) {
  if (!a || !b) {
    console.log(chalk.red('  Error: two concept names required.'));
    console.log(chalk.dim('  Usage: bizar graph path "<A>" "<B>"\n'));
    return 1;
  }
  return runGraphify(python, ['path', a, b]);
}

async function cmdExplain(python, concept) {
  if (!concept) {
    console.log(chalk.red('  Error: concept name required.'));
    console.log(chalk.dim('  Usage: bizar graph explain "<X>"\n'));
    return 1;
  }
  return runGraphify(python, ['explain', concept]);
}

async function cmdWatch(python) {
  console.log(chalk.dim('  Starting graphify watch mode (Ctrl-C to stop)...'));
  return runGraphify(python, ['.', '--watch']);
}

async function cmdStatus() {
  const graphJsonPath = join(GRAPH_DIR, 'graph.json');
  const stats = parseGraphStats(graphJsonPath);

  console.log(chalk.bold.hex('#10b981')('\n  ᛗ BIZAR GRAPH STATUS ᛗ\n'));
  console.log(`  Path:       ${GRAPH_DIR}/`);

  if (!existsSync(GRAPH_DIR)) {
    console.log(`  Exists:     ${chalk.yellow('no')}  (run \`bizar graph build\` first)`);
    console.log();
    return 0;
  }

  if (!stats) {
    console.log(`  Exists:     ${chalk.yellow('no graph.json found')}`);
    console.log();
    return 0;
  }

  console.log(`  Exists:     ${chalk.green('yes')}`);
  console.log(`  Size:       ${(stats.sizeBytes / 1024).toFixed(1)} KB`);
  console.log(`  Last built: ${stats.lastModified}`);
  console.log(`  Nodes:      ${stats.nodes}`);
  console.log(`  Edges:      ${stats.edges}`);
  console.log(`  Communities:${stats.communities}`);
  console.log();
  return 0;
}

async function cmdInstall() {
  const python = findPython();
  if (!python) {
    console.error(chalk.red('  Error: graphify requires Python 3.10+.'));
    console.error(chalk.dim('  Install Python from https://python.org or via your package manager, then re-run.\n'));
    return 1;
  }

  // Prefer uv (handles PEP 668 isolated installs cleanly); fall back to pip.
  const { detectUv } = await import('./utils.mjs');
  const hasUv = await detectUv();

  if (hasUv) {
    console.log(chalk.dim('  Installing graphify via uv...\n'));
    const result = spawnSync('uv', ['tool', 'install', 'graphifyy'], { stdio: 'inherit' });
    if (result.status !== 0) {
      console.log(chalk.red('  ✗ uv tool install graphifyy failed.\n'));
      return 1;
    }
  } else {
    console.log(chalk.dim('  Installing graphify via pip...\n'));
    // On Windows `pip` may not be on PATH; use `py -m pip` as the fallback.
    const pipCmd = process.platform === 'win32'
      ? [python, '-m', 'pip']
      : ['pip'];
    const result = spawnSync(pipCmd[0], pipCmd.slice(1).concat(['install', 'graphifyy']), { stdio: 'inherit' });
    if (result.status !== 0) {
      console.log(chalk.red('  ✗ pip install graphifyy failed.\n'));
      return 1;
    }
  }

  // graphify install --platform opencode --project
  console.log(chalk.dim('\n  $ graphify install --platform opencode --project'));
  const result = spawnSync('graphify', ['install', '--platform', 'opencode', '--project'], {
    stdio: 'inherit',
  });
  if (result.status !== 0) {
    console.log(chalk.red('  ✗ graphify install failed.\n'));
    return 1;
  }

  console.log(chalk.green('\n  ✓ graphify installed and OpenCode plugin configured.\n'));
  return 0;
}

// ── Help ──────────────────────────────────────────────────────────────────────

export function showGraphHelp() {
  console.log(`
  ${chalk.bold.hex('#10b981')('bizar graph')} — Per-project knowledge graph (powered by graphify)

  ${chalk.dim('Usage:')}
    ${chalk.cyan('bizar graph build')}              # full build of the project graph
    ${chalk.cyan('bizar graph update')}              # incremental rebuild
    ${chalk.cyan('bizar graph query "<text>"')}    # query the graph
    ${chalk.cyan('bizar graph path "<A>" "<B>"')}  # shortest path between concepts
    ${chalk.cyan('bizar graph explain "<X>"')}     # all nodes related to a concept
    ${chalk.cyan('bizar graph watch')}              # watch for changes and rebuild
    ${chalk.cyan('bizar graph status')}             # show graph path, size, node/edge/community counts
    ${chalk.cyan('bizar graph install')}            # install graphify + drop OpenCode skill/plugin

  ${chalk.dim('Requires:')} Python 3.10+ and \`graphify\` (${chalk.cyan('pip install graphifyy')})

  ${chalk.dim('Graph data lives in')} ${chalk.cyan('.bizar/graph/')} ${chalk.dim('inside this project.')}
  `);
}

// ── Main entry point ───────────────────────────────────────────────────────────

/**
 * `bizar graph` entry point.
 *
 * @param {string[]} args — subcommand + args after 'graph'
 */
export async function runGraph(args) {
  // Show help when called with no args or --help / -h
  if (args.length === 0 || args.includes('--help') || args.includes('-h')) {
    showGraphHelp();
    return 0;
  }

  const sub = args[0];

  // status and install are the only subcommands that don't need graphify
  if (sub !== 'status' && sub !== 'install') {
    // Detect Python
    const python = findPython();
    if (!python) {
      console.error(chalk.red('  Error: graphify requires Python 3.10+.'));
      console.error(chalk.dim('  Install Python from https://python.org or via your package manager, then re-run.\n'));
      return 1;
    }

    // Detect graphify
    if (!checkGraphify(python)) {
      console.error(chalk.red('  Error: graphify is not installed.'));
      console.error(chalk.dim('  Install it with:'));
      console.error(chalk.cyan('    pip install graphifyy\n'));
      console.error(chalk.dim('  Or run:'));
      console.error(chalk.cyan('    bizar graph install\n'));
      return 1;
    }

    // Ensure .bizar/ directory exists (graphify will create graph/ inside it)
    mkdirSync(GRAPH_DIR, { recursive: true });

    switch (sub) {
      case 'build':
        return await cmdBuild(python);
      case 'update':
        return await cmdUpdate(python);
      case 'query':
        return await cmdQuery(python, args.slice(1).join(' '));
      case 'path':
        return await cmdPath(python, args[1], args[2]);
      case 'explain':
        return await cmdExplain(python, args[1]);
      case 'watch':
        return await cmdWatch(python);
      default:
        console.error(chalk.red(`  Error: unknown subcommand '${sub}'.\n`));
        showGraphHelp();
        return 1;
    }
  }

  // subcommands that don't need graphify
  switch (sub) {
    case 'status':
      return await cmdStatus();
    case 'install':
      return await cmdInstall();
    default:
      // unreachable — already caught unknown subcommands above
      return 1;
  }
}
