/**
 * cli/service-env.mjs
 *
 * v5.x — Central env file builder for the Bizar service.
 *
 * Produces the content for `~/.config/bizar/service.env` (mode 0600),
 * which is sourced by the systemd/launchd service.
 *
 * All BIZAR_* vars are written here so the service has a consistent view
 * of the environment. Values already present in `process.env` are honoured
 * (never overwritten); everything else gets a safe default.
 *
 * Public API:
 *   buildServiceEnvFile({ bizarHome, repoPath, options })
 *     → string  (the env file content, ready to write)
 *   defaultBizarEnv()
 *     → Record<string, string>  (all defaults merged)
 */

import { execSync } from 'node:child_process';
import { existsSync, readSync, closeSync, openSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

/** Default values for every BIZAR_* env var. */
export function defaultBizarEnv() {
  const home = homedir();
  return {
    BIZAR_HOME: join(home, '.config', 'bizar'),
    BIZAR_REPO: '',
    BIZAR_DASHBOARD_PORT: '4097',
    BIZAR_DASHBOARD_HOST: '127.0.0.1',
    BIZAR_LOG_LEVEL: 'info',
    BIZAR_LIGHTRAG_AUTOSTART: '1',
    BIZAR_MEMORY_VAULT: join(home, '.bizar_memory'),
    CLINE_SERVER_PASSWORD: '',
  };
}

/**
 * Generate a fresh `CLINE_SERVER_PASSWORD` using the platform's
 * secure random source.
 */
function generatePassword() {
  try {
    if (process.platform === 'win32') {
      // PowerShell
      const out = execSync(
        'powershell -Command "[Convert]::ToBase64String((1..32 | ForEach-Object { Get-Random -Maximum 256 }))"',
        { encoding: 'utf8', timeout: 5000 },
      );
      return out.trim().replace(/\n/g, '');
    }
    // Linux/macOS
    const out = execSync('openssl rand -hex 32', { encoding: 'utf8', timeout: 5000 });
    return out.trim();
  } catch {
    // Fallback: rough approximation using /dev/urandom
    try {
      const fd = openSync('/dev/urandom', 'r');
      if (fd !== undefined) {
        const buf = Buffer.alloc(32);
        readSync(fd, buf, 0, 32);
        closeSync(fd);
        return buf.toString('hex');
      }
    } catch { /* ignore */ }
    // Last-resort: use Date.now() + PID — not great but better than nothing
    return `${Date.now()}-${process.pid}`.split('').reverse().join('').slice(0, 64);
  }
}

/**
 * Build the service.env file content.
 *
 * @param {object} opts
 * @param {string} [opts.bizarHome]   – default: ~/.config/bizar
 * @param {string} [opts.repoPath]    – absolute path to the repo root
 * @param {boolean} [opts.lightragAutoStart] – default: true
 * @returns {string} env file content (does NOT write to disk)
 */
export function buildServiceEnvFile({ bizarHome, repoPath, lightragAutoStart = true } = {}) {
  const home = homedir();
  const defaults = defaultBizarEnv();

  const env = {
    BIZAR_HOME:        bizarHome    || defaults.BIZAR_HOME,
    BIZAR_REPO:        repoPath     || process.env.BIZAR_REPO || '',
    BIZAR_DASHBOARD_PORT:  process.env.BIZAR_DASHBOARD_PORT  || defaults.BIZAR_DASHBOARD_PORT,
    BIZAR_DASHBOARD_HOST:  process.env.BIZAR_DASHBOARD_HOST  || defaults.BIZAR_DASHBOARD_HOST,
    BIZAR_LOG_LEVEL:       process.env.BIZAR_LOG_LEVEL       || defaults.BIZAR_LOG_LEVEL,
    BIZAR_LIGHTRAG_AUTOSTART: String(
      process.env.BIZAR_LIGHTRAG_AUTOSTART !== undefined
        ? (process.env.BIZAR_LIGHTRAG_AUTOSTART === '1' || process.env.BIZAR_LIGHTRAG_AUTOSTART === 'true' ? '1' : '0')
        : (lightragAutoStart ? '1' : '0')
    ),
    BIZAR_MEMORY_VAULT: process.env.BIZAR_MEMORY_VAULT || defaults.BIZAR_MEMORY_VAULT,
  };

  // Always add ~/.local/bin to PATH for uv tool binaries (lightrag-server, etc.)
  const localBin = join(home, '.local', 'bin');
  const existingPath = process.env.PATH || '/usr/local/bin:/usr/bin:/bin';
  env.PATH = existingPath.includes(localBin) ? existingPath : `${localBin}:${existingPath}`;

  // CLINE_SERVER_PASSWORD: honour existing env, otherwise generate fresh
  const password = process.env.CLINE_SERVER_PASSWORD
    || process.env.BIZAR_REDACT_PASSWORD === '1' ? ''
    : (process.env.CLINE_SERVER_PASSWORD || generatePassword());
  if (password) {
    env.CLINE_SERVER_PASSWORD = password;
  }

  const lines = [
    '# Generated by bizar service install — edit with care.',
    `# Created: ${new Date().toISOString()}`,
    `BIZAR_HOME=${env.BIZAR_HOME}`,
    `BIZAR_REPO=${env.BIZAR_REPO}`,
    `PATH=${env.PATH}`,
    `BIZAR_DASHBOARD_PORT=${env.BIZAR_DASHBOARD_PORT}`,
    `BIZAR_DASHBOARD_HOST=${env.BIZAR_DASHBOARD_HOST}`,
    `BIZAR_LOG_LEVEL=${env.BIZAR_LOG_LEVEL}`,
    `BIZAR_HEADROOM_AUTOSTART=${env.BIZAR_HEADROOM_AUTOSTART}`,
    `BIZAR_LIGHTRAG_AUTOSTART=${env.BIZAR_LIGHTRAG_AUTOSTART}`,
    `BIZAR_MEMORY_VAULT=${env.BIZAR_MEMORY_VAULT}`,
  ];
  if (password) {
    lines.push(`CLINE_SERVER_PASSWORD=${password}`);
  }

  return lines.join('\n') + '\n';
}
