/**
 * cli/commands/deploy/cloudflare.mjs
 *
 * Cloudflare Pages + Workers deployment via REST API.
 *
 * Generates wrangler.toml + functions/ (Workers entry) + public/ (static),
 * then uploads to Cloudflare Pages API or runs wrangler CLI.
 */
import chalk from 'chalk';
import { existsSync, mkdirSync, writeFileSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

const API_BASE = 'https://api.cloudflare.com/client/v4';

// ── Scaffold generation ──────────────────────────────────────────────────────

function generateScaffold(outDir, opts) {
  const scaffoldRoot = join(outDir, 'cloudflare');

  if (!existsSync(scaffoldRoot)) {
    mkdirSync(scaffoldRoot, { recursive: true });
  }

  // wrangler.toml
  const wranglerContent = [
    'name = "' + (opts.projectName || 'bizar-dash') + '"',
    'main = "functions/index.js"',
    'compatibility_date = "2025-01-01"',
    '',
    '[site]',
    '  bucket = "./public"',
    '',
    '[env.production]',
    '  routes = ["' + (opts.projectName || 'bizar-dash') + '.*.pages.dev/*"]',
    '',
  ].join('\n');
  writeFileSync(join(scaffoldRoot, 'wrangler.toml'), wranglerContent);

  // functions/index.js — Workers function entry
  const fnDir = join(scaffoldRoot, 'functions');
  if (!existsSync(fnDir)) mkdirSync(fnDir, { recursive: true });

  const functionsIndex = [
    '// Cloudflare Workers entry — Bizar dashboard',
    '// Generated by `bizar deploy --to cloudflare`',
    '',
    'export async function onRequest(context) {',
    '  const { request, env } = context;',
    '  const url = new URL(request.url);',
    '',
    '  // Serve static assets from Pages KV',
    '  if (url.pathname.startsWith("/assets/")) {',
    '    return env.ASSETS.fetch(request);',
    '  }',
    '',
    '  // SPA fallback',
    '  return env.ASSETS.fetch(new Request(url.origin + "/index.html", request));',
    '}',
    '',
  ].join('\n');
  writeFileSync(join(fnDir, 'index.js'), functionsIndex);

  // public/ — placeholder for dashboard build output
  const publicDir = join(scaffoldRoot, 'public');
  if (!existsSync(publicDir)) mkdirSync(publicDir, { recursive: true });

  // Build the dashboard
  console.log(chalk.dim('  Building dashboard bundle\u2026'));
  try {
    execSync('npm run build', {
      cwd: opts.projectRoot,
      encoding: 'utf8',
      stdio: 'pipe',
      timeout: 120000,
    });
  } catch (err) {
    throw new Error('Dashboard build failed: ' + err.message);
  }

  // Copy built assets into public/
  const distDir = join(opts.projectRoot, 'dist');
  if (existsSync(distDir)) {
    execSync('cp -r "' + distDir + '"/* "' + publicDir + '/"', { stdio: 'pipe' });
  } else {
    console.log(chalk.yellow('  \u26a0 No dist/ found \u2014 deploying scaffold only'));
  }

  console.log(chalk.dim('  \u2713 Scaffold generated at', scaffoldRoot));
  return scaffoldRoot;
}

// ── API helpers ──────────────────────────────────────────────────────────────

async function cfPost(path, token, body) {
  const url = API_BASE + path;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: 'Bearer ' + token,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  const json = await res.json();
  if (!json.success) {
    const msgs = (json.errors || []).map((e) => e.message).join('; ');
    throw new Error('Cloudflare API error: ' + msgs || 'HTTP ' + res.status);
  }
  return json.result;
}

async function cfGet(path, token) {
  const url = API_BASE + path;
  const res = await fetch(url, {
    headers: { Authorization: 'Bearer ' + token },
  });
  const json = await res.json();
  if (!json.success) {
    const msgs = (json.errors || []).map((e) => e.message).join('; ');
    throw new Error('Cloudflare API error: ' + msgs || 'HTTP ' + res.status);
  }
  return json.result;
}

// ── Deployment ───────────────────────────────────────────────────────────────

export async function deployToCloudflare({ token, projectName, projectRoot, outDir }) {
  if (!token) {
    throw new Error('Cloudflare token required. Pass --token or set CLOUDFLARE_API_TOKEN env var.');
  }

  // 1. Generate scaffold
  const scaffoldRoot = generateScaffold(outDir, { projectName, projectRoot });
  const name = projectName || 'bizar-dash';

  // 2. Try wrangler CLI first (most reliable)
  const hasWrangler = await checkWrangler();
  if (hasWrangler) {
    console.log(chalk.dim('  Deploying with wrangler CLI\u2026'));
    try {
      const output = execSync('npx wrangler pages deploy "' + scaffoldRoot + '" --project-name "' + name + '"' + (token ? ' --api-token ' + token : ''), {
        cwd: scaffoldRoot,
        encoding: 'utf8',
        stdio: 'pipe',
        timeout: 120000,
      });
      const urlMatch = output.match(/https:\/\/[^\s]+\.pages\.dev/);
      const url = urlMatch ? urlMatch[0] : null;
      if (url) {
        return {
          url,
          deploymentId: name,
          notes: ['Deployed via wrangler CLI.'],
        };
      }
      return {
        url: 'https://' + name + '.pages.dev',
        deploymentId: name,
        notes: ['Deployment complete. Check wrangler output for details.'],
      };
    } catch (err) {
      throw new Error('wrangler deploy failed: ' + err.message);
    }
  }

  // 3. Fallback: use Cloudflare Pages API directly
  console.log(chalk.dim('  Deploying via Cloudflare API\u2026'));

  // List accounts to find the first one
  const accounts = await cfGet('/accounts', token);
  if (!accounts || accounts.length === 0) {
    throw new Error('No Cloudflare account found');
  }
  const accountId = accounts[0].id;

  // Create or get the Pages project
  let project;
  try {
    project = await cfPost('/accounts/' + accountId + '/pages/projects', token, {
      name,
      production_branch: 'main',
    });
  } catch {
    // Project may already exist — look it up
    project = await cfGet('/accounts/' + accountId + '/pages/projects/' + name, token);
  }

  if (!project) {
    throw new Error('Could not create or find Cloudflare Pages project: ' + name);
  }

  // Upload files
  const files = collectFiles(scaffoldRoot);
  const uploadResult = await cfPost('/accounts/' + accountId + '/pages/projects/' + name + '/upload', token, {
    files,
  });

  // Start deployment
  const deployment = await cfPost('/accounts/' + accountId + '/pages/projects/' + name + '/deployments', token, {
    manifest: uploadResult.manifest || {},
  });

  const subdomain = project.subdomain || (name + '.pages.dev');
  return {
    url: 'https://' + subdomain,
    deploymentId: deployment.id || name,
    notes: [
      'Cloudflare Pages project: ' + name,
      'Manage at https://dash.cloudflare.com/?to=/:account/pages/view/' + name,
    ],
  };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

async function checkWrangler() {
  try {
    execSync('npx wrangler --version', {
      encoding: 'utf8',
      stdio: 'pipe',
      timeout: 10000,
    });
    return true;
  } catch {
    return false;
  }
}

function collectFiles(rootDir) {
  const files = [];

  function walk(dir, prefix) {
    const entries = readdirSync(dir);
    for (const entry of entries) {
      const full = join(dir, entry);
      const rel = prefix ? prefix + '/' + entry : entry;
      const stat = statSync(full);
      if (stat.isDirectory()) {
        walk(full, rel);
      } else {
        const content = readFileSync(full, 'base64');
        files.push({ file: rel, data: content, encoding: 'base64' });
      }
    }
  }

  walk(rootDir, '');
  return files;
}
