/**
 * cli/commands/deploy/docker.mjs
 *
 * Docker registry push deployment.
 *
 * Builds image: `docker build -t <registry>/<name>:<version> .`
 * Pushes: `docker push <registry>/<name>:<version>`
 * Optionally generates docker-compose.yml + .env for self-host.
 */
import chalk from 'chalk';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

// ── Scaffold generation ──────────────────────────────────────────────────────

function generateComposeScaffold(outDir, opts) {
  const scaffoldRoot = join(outDir, 'docker');

  if (!existsSync(scaffoldRoot)) {
    mkdirSync(scaffoldRoot, { recursive: true });
  }

  // docker-compose.yml
  const imageRef = (opts.registry || 'ghcr.io') + '/' + (opts.imageName || 'bizar-dash');

  const composeYml = [
    '# docker-compose.yml — Bizar dashboard',
    '# Generated by `bizar deploy --to docker --compose`',
    '',
    'version: "3.8"',
    '',
    'services:',
    '  bizar-dash:',
    '    image: ' + imageRef + ':latest',
    '    container_name: bizar-dash',
    '    restart: unless-stopped',
    '    ports:',
    '      - "4097:4097"',
    '      - "4098:4098"',
    '    environment:',
    '      - BIZAR_DASHBOARD_PORT=4097',
    '      - BIZAR_DASHBOARD_HOST=0.0.0.0',
    '      - NODE_ENV=production',
    '    env_file:',
    '      - .env',
    '    volumes:',
    '      - bizar-config:/home/bizar/.config/bizar',
    '      - bizar-memory:/home/bizar/.local/share/bizar/memory',
    '',
    'volumes:',
    '  bizar-config:',
    '  bizar-memory:',
    '',
  ].join('\n');
  writeFileSync(join(scaffoldRoot, 'docker-compose.yml'), composeYml);

  // .env template
  const envTemplate = [
    '# .env — Bizar dashboard environment variables',
    '# Generated by `bizar deploy --to docker --compose`',
    '#',
    '# Copy this file to .env and fill in your values.',
    '',
    '# Dashboard',
    '# BIZAR_DASHBOARD_PORT=4097',
    '# BIZAR_DASHBOARD_HOST=0.0.0.0',
    '',
    '# OpenTelemetry (optional)',
    '# BIZAR_OTEL=1',
    '# OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4318',
    '',
    '# Tailscale (optional)',
    '# TAILSCALE_AUTHKEY=tskey-auth-xxxxxxxxxxxxxxxxxxxx',
    '',
    '# Headroom context compression (optional)',
    '# HEADROOM_ENABLED=1',
    '',
  ].join('\n');
  writeFileSync(join(scaffoldRoot, '.env.template'), envTemplate);

  console.log(chalk.dim('  \u2713 Docker Compose scaffold generated at', scaffoldRoot));
  return scaffoldRoot;
}

// ── Docker daemon check ──────────────────────────────────────────────────────

function checkDocker() {
  try {
    execSync('docker info', {
      encoding: 'utf8',
      stdio: 'pipe',
      timeout: 5000,
    });
    return true;
  } catch {
    return false;
  }
}

// ── Deployment ───────────────────────────────────────────────────────────────

export async function deployToDocker({ token, registry, imageName, projectRoot, outDir, compose }) {
  // Handle --compose only mode
  if (compose) {
    const scaffoldRoot = generateComposeScaffold(outDir, { registry, imageName });
    return {
      url: null,
      deploymentId: null,
      notes: [
        'Docker Compose files generated at ' + scaffoldRoot,
        'To run: cd ' + scaffoldRoot + ' && docker compose up -d',
        'To customize, edit docker-compose.yml and .env',
      ],
    };
  }

  // Full build + push
  if (!checkDocker()) {
    throw new Error(
      'Docker daemon is not running. Start Docker and try again.\n' +
      '  systemctl start docker   (Linux)\n' +
      '  open -a Docker           (macOS)',
    );
  }

  const reg = registry || 'ghcr.io';
  const imgName = imageName || 'bizar-dash';
  const version = getPackageVersion(projectRoot);
  const imageRef = reg + '/' + imgName;
  const tag = imageRef + ':' + version;
  const latestTag = imageRef + ':latest';

  // 1. Build the image
  console.log(chalk.dim('  Building Docker image\u2026'));
  try {
    execSync('docker build -t "' + tag + '" -t "' + latestTag + '" .', {
      cwd: projectRoot,
      encoding: 'utf8',
      stdio: 'pipe',
      timeout: 300000, // 5 minutes
    });
  } catch (err) {
    throw new Error('Docker build failed: ' + err.message);
  }

  // 2. Login if token provided
  if (token) {
    console.log(chalk.dim('  Authenticating with registry\u2026'));
    const loginCmd = 'docker login ' + reg + ' --username=oauth --password-stdin';
    try {
      execSync(loginCmd, {
        input: token,
        encoding: 'utf8',
        stdio: ['pipe', 'pipe', 'pipe'],
        timeout: 15000,
      });
    } catch (err) {
      throw new Error('Docker login failed: ' + err.message);
    }
  }

  // 3. Push the image
  console.log(chalk.dim('  Pushing image to ' + reg + '\u2026'));
  try {
    execSync('docker push "' + tag + '"', {
      encoding: 'utf8',
      stdio: 'pipe',
      timeout: 300000,
    });
    execSync('docker push "' + latestTag + '"', {
      encoding: 'utf8',
      stdio: 'pipe',
      timeout: 300000,
    });
  } catch (err) {
    throw new Error('Docker push failed: ' + err.message);
  }

  const digest = getDigest(imageRef);
  return {
    url: null,
    deploymentId: tag,
    notes: [
      'Image: ' + tag,
      'Latest: ' + latestTag,
      (digest ? 'Digest: ' + digest : ''),
      '',
      'To pull: docker pull ' + tag,
      'To run:  docker run -p 4097:4097 ' + tag,
      'To compose: bizar deploy --to docker --compose',
    ].filter(Boolean),
  };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function getPackageVersion(projectRoot) {
  try {
    const pkg = JSON.parse(readFileSync(join(projectRoot, 'package.json'), 'utf8'));
    return pkg.version || 'latest';
  } catch {
    return 'latest';
  }
}

function getDigest(imageRef) {
  try {
    const output = execSync('docker inspect --format="{{.RepoDigests}}" "' + imageRef + '"', {
      encoding: 'utf8',
      stdio: 'pipe',
      timeout: 5000,
    });
    const match = output.match(/sha256:[a-f0-9]{64}/);
    return match ? match[0] : null;
  } catch {
    return null;
  }
}


