/**
 * cli/commands/deploy/fly.mjs
 *
 * Fly.io deployment via flyctl CLI.
 *
 * Generates fly.toml, optionally uses existing Dockerfile (v4.9),
 * then runs `flyctl deploy`.
 */
import chalk from 'chalk';
import { existsSync, mkdirSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

// ── Scaffold generation ──────────────────────────────────────────────────────

function generateScaffold(outDir, opts) {
  const scaffoldRoot = join(outDir, 'fly');

  if (!existsSync(scaffoldRoot)) {
    mkdirSync(scaffoldRoot, { recursive: true });
  }

  // fly.toml
  const flyToml = [
    '# fly.toml — Bizar dashboard',
    '# Generated by `bizar deploy --to fly`',
    '',
    'app = "' + (opts.appName || 'bizar-dash') + '"',
    '',
    'primary_region = "' + (opts.region || 'iad') + '"',
    '',
    '[build]',
    '  dockerfile = "../Dockerfile"',
    '',
    '[http_service]',
    '  internal_port = 4097',
    '  force_https = true',
    '  auto_stop_machines = true',
    '  auto_start_machines = true',
    '  min_machines_running = 0',
    '',
    '[[vm]]',
    '  memory = "512mb"',
    '  cpu_kind = "shared"',
    '  cpus = 1',
    '',
    '[env]',
    '  BIZAR_DASHBOARD_PORT = "4097"',
    '  BIZAR_DASHBOARD_HOST = "0.0.0.0"',
    '  NODE_ENV = "production"',
    '',
    '[deploy]',
    '  strategy = "rolling"',
    '',
  ].join('\n');
  writeFileSync(join(scaffoldRoot, 'fly.toml'), flyToml);

  console.log(chalk.dim('  \u2713 Scaffold generated at', scaffoldRoot));
  return scaffoldRoot;
}

// ── Deployment ───────────────────────────────────────────────────────────────

export async function deployToFly({ token, appName, region, projectRoot, outDir }) {
  // Check that flyctl is installed
  const flyctlPath = checkFlyctl();
  if (!flyctlPath) {
    throw new Error(
      'flyctl not found. Install it first:\n' +
      '  curl -L https://fly.io/install.sh | sh\n' +
      '  Or download from https://fly.io/docs/getting-started/installing-flyctl/',
    );
  }

  // Check Dockerfile exists (v4.9 work)
  const dockerfilePath = join(projectRoot, 'Dockerfile');
  if (!existsSync(dockerfilePath)) {
    console.log(chalk.yellow('  \u26a0 No Dockerfile found at project root. Fly.io requires one.'));
  }

  // 1. Generate scaffold
  const scaffoldRoot = generateScaffold(outDir, { appName, region });
  const name = appName || 'bizar-dash';

  // 2. Check if app exists; if not, launch it
  try {
    execSync(flyctlPath + ' apps list', {
      encoding: 'utf8',
      stdio: 'pipe',
      timeout: 15000,
    });
  } catch {
    console.log(chalk.dim('  App not found. Launching new app\u2026'));
    try {
      execSync(flyctlPath + ' launch --name "' + name + '" --region "' + (region || 'iad') + '" --no-deploy --now', {
        cwd: projectRoot,
        encoding: 'utf8',
        stdio: 'pipe',
        timeout: 60000,
      });
    } catch (err) {
      throw new Error('flyctl launch failed: ' + err.message);
    }
  }

  // 3. Check auth
  if (!token) {
    // flyctl uses its own auth — the --token flag may not be needed for flyctl
    console.log(chalk.dim('  No FLY_API_TOKEN set. flyctl will use its own auth.'));
  }

  // 4. Deploy
  console.log(chalk.dim('  Deploying to Fly.io\u2026'));
  const deployCmd = flyctlPath + ' deploy' +
    ' --app "' + name + '"' +
    ' --strategy rolling' +
    (token ? ' --access-token "' + token + '"' : '') +
    ' --remote-only';

  try {
    execSync(deployCmd, {
      cwd: projectRoot,
      encoding: 'utf8',
      stdio: 'pipe',
      timeout: 300000, // 5 minutes for build + deploy
    });
  } catch (err) {
    throw new Error('flyctl deploy failed: ' + err.message);
  }

  // 5. Get the app URL
  const appUrl = 'https://' + name + '.fly.dev';
  return {
    url: appUrl,
    deploymentId: name,
    notes: [
      'Region: ' + (region || 'iad'),
      'Run `flyctl status --app ' + name + '` for details.',
    ],
  };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

function checkFlyctl() {
  // Check common locations
  const candidates = ['flyctl', 'fly'];
  for (const cmd of candidates) {
    try {
      const result = execSync('which ' + cmd, {
        encoding: 'utf8',
        stdio: 'pipe',
        timeout: 3000,
      });
      if (result.trim()) return cmd;
    } catch {
      // try next
    }
  }
  return null;
}
