/**
 * cli/commands/deploy/vercel.mjs
 *
 * Vercel deployment via REST API.
 *
 * Generates vercel.json + api/index.js (serverless function entry) +
 * public/ (static dashboard bundle), then POSTs to Vercel Deployments API.
 */
import chalk from 'chalk';
import { existsSync, mkdirSync, writeFileSync, readFileSync, readdirSync, statSync } from 'node:fs';
import { join } from 'node:path';
import { execSync } from 'node:child_process';

const API_BASE = 'https://api.vercel.com';

// ── Scaffold generation ──────────────────────────────────────────────────────

function generateScaffold(outDir, opts) {
  const scaffoldRoot = join(outDir, 'vercel');

  if (!existsSync(scaffoldRoot)) {
    mkdirSync(scaffoldRoot, { recursive: true });
  }

  // vercel.json
  const vercelJson = {
    name: opts.projectName || 'bizar-dash',
    version: 2,
    buildCommand: 'npm run build',
    outputDirectory: 'public',
    routes: [
      { src: '/api/(.*)', dest: '/api/index.js' },
      { src: '/(.*)', dest: '/public/$1' },
    ],
    functions: {
      'api/index.js': {
        memory: 256,
        maxDuration: 30,
      },
    },
  };
  writeFileSync(join(scaffoldRoot, 'vercel.json'), JSON.stringify(vercelJson, null, 2));

  // api/index.js — serverless entry that serves the dashboard
  const apiDir = join(scaffoldRoot, 'api');
  if (!existsSync(apiDir)) mkdirSync(apiDir, { recursive: true });

  const apiIndexContent = [
    '// Vercel serverless entry — Bizar dashboard',
    '// Generated by `bizar deploy --to vercel`',
    "import express from 'express';",
    "import { join, dirname } from 'node:path';",
    "import { fileURLToPath } from 'node:url';",
    '',
    'const __dirname = dirname(fileURLToPath(import.meta.url));',
    'const app = express();',
    '',
    '// Serve static files from the dashboard build',
    "app.use(express.static(join(__dirname, '..', 'public')));",
    '',
    '// Fallback to index.html for SPA routing',
    "app.get('*', (_req, res) => {",
    "  res.sendFile(join(__dirname, '..', 'public', 'index.html'));",
    '});',
    '',
    'export default app;',
    '',
  ].join('\n');
  writeFileSync(join(apiDir, 'index.js'), apiIndexContent);

  // Build the dashboard bundle into public/
  const publicDir = join(scaffoldRoot, 'public');
  if (!existsSync(publicDir)) mkdirSync(publicDir, { recursive: true });

  console.log(chalk.dim('  Building dashboard bundle\u2026'));
  try {
    execSync('npm run build', {
      cwd: opts.projectRoot,
      encoding: 'utf8',
      stdio: 'pipe',
      timeout: 120000,
    });
  } catch (err) {
    throw new Error('Dashboard build failed: ' + err.message);
  }

  // Copy built assets into public/
  const distDir = join(opts.projectRoot, 'dist');
  if (existsSync(distDir)) {
    execSync('cp -r "' + distDir + '"/* "' + publicDir + '/"', { stdio: 'pipe' });
  } else {
    console.log(chalk.yellow('  \u26a0 No dist/ found \u2014 deploying scaffold only'));
  }

  console.log(chalk.dim('  \u2713 Scaffold generated at', scaffoldRoot));
  return scaffoldRoot;
}

// ── API helpers ──────────────────────────────────────────────────────────────

async function vercelPost(path, token, body) {
  const url = API_BASE + path;
  const res = await fetch(url, {
    method: 'POST',
    headers: {
      Authorization: 'Bearer ' + token,
      'Content-Type': 'application/json',
    },
    body: JSON.stringify(body),
  });
  const text = await res.text();
  let json = null;
  try { json = text ? JSON.parse(text) : null; } catch { /* keep raw */ }
  if (!res.ok) {
    const msg = json?.error?.message || json?.error?.code || text || 'HTTP ' + res.status;
    throw new Error('Vercel API error: ' + msg);
  }
  return json;
}

async function vercelGet(path, token) {
  const url = API_BASE + path;
  const res = await fetch(url, {
    headers: { Authorization: 'Bearer ' + token },
  });
  const text = await res.text();
  let json = null;
  try { json = text ? JSON.parse(text) : null; } catch { /* keep raw */ }
  if (!res.ok) {
    const msg = json?.error?.message || json?.error?.code || text || 'HTTP ' + res.status;
    throw new Error('Vercel API error: ' + msg);
  }
  return json;
}

// ── Deployment ───────────────────────────────────────────────────────────────

export async function deployToVercel({ token, projectName, projectRoot, outDir }) {
  if (!token) {
    throw new Error('Vercel token required. Pass --token or set VERCEL_TOKEN env var.');
  }

  // 1. Generate scaffold
  const scaffoldRoot = generateScaffold(outDir, { projectName, projectRoot });
  const name = projectName || 'bizar-dash';

  // 2. Upload to Vercel
  console.log(chalk.dim('  Uploading to Vercel\u2026'));

  const body = {
    name,
    deploymentType: 'instant',
    files: collectFiles(scaffoldRoot),
    projectSettings: {
      framework: 'other',
      installCommand: 'npm install',
      buildCommand: 'npm run build',
      outputDirectory: 'public',
    },
  };

  const result = await vercelPost('/v13/deployments', token, body);

  // 3. Poll for ready state
  const deploymentId = result.id || result.uid;
  if (!deploymentId) {
    throw new Error('No deployment ID returned from Vercel');
  }

  console.log(chalk.dim('  Deployment ID:', deploymentId));

  // Poll up to 60 seconds
  for (let i = 0; i < 30; i++) {
    const status = await vercelGet('/v13/deployments/' + deploymentId, token);
    const state = status.readyState || status.state;
    if (state === 'READY') {
      const url = status.url || 'https://' + deploymentId + '.vercel.app';
      return {
        url: 'https://' + url,
        deploymentId,
        notes: ['Open the URL in your browser to view your dashboard'],
      };
    }
    if (state === 'ERROR' || state === 'CANCELED') {
      throw new Error('Deployment failed with state: ' + state);
    }
    // Wait 2 seconds before polling again
    await new Promise((r) => setTimeout(r, 2000));
  }

  // Timeout — return whatever we have
  return {
    url: 'https://' + deploymentId + '.vercel.app',
    deploymentId,
    notes: ['Deployment is still building. Check the Vercel dashboard for status.'],
  };
}

// ── Helpers ──────────────────────────────────────────────────────────────────

/**
 * Collect files from a directory for the Vercel API.
 * Returns an array of { file, data } objects (base64-encoded).
 */
function collectFiles(rootDir) {
  const files = [];

  function walk(dir, prefix) {
    const entries = readdirSync(dir);
    for (const entry of entries) {
      const full = join(dir, entry);
      const rel = prefix ? prefix + '/' + entry : entry;
      const stat = statSync(full);
      if (stat.isDirectory()) {
        walk(full, rel);
      } else {
        const content = readFileSync(full, 'base64');
        files.push({ file: rel, data: content, encoding: 'base64' });
      }
    }
  }

  walk(rootDir, '');
  return files;
}
