/**
 * cli/commands/sandbox.mjs — `bizar sandbox` wrapper for CubeSandbox.
 *
 * v6.3.0 — first-class CubeSandbox integration.
 *
 * Subcommands:
 *   bizar sandbox run <lang> <script>      Run a script in a fresh sandbox.
 *   bizar sandbox shell <lang> <script...> Run an interactive shell script.
 *   bizar sandbox list                     List active sandboxes.
 *   bizar sandbox kill <id>                Kill a running sandbox.
 *   bizar sandbox doctor                   Verify SDK + control-node reachability.
 *   bizar sandbox install-template <name>  Install a template from Template Store.
 *
 * Sandboxes are E2B-compatible. We use the official Python SDK
 * (`pip install cubesandbox`) through a thin subprocess wrapper so the
 * CLI stays JS-only.
 */
import { spawnSync } from 'node:child_process';
import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';

const COLOR = {
  red: (s) => `\x1b[31m${s}\x1b[0m`,
  green: (s) => `\x1b[32m${s}\x1b[0m`,
  yellow: (s) => `\x1b[33m${s}\x1b[0m`,
  cyan: (s) => `\x1b[36m${s}\x1b[0m`,
  gray: (s) => `\x1b[90m${s}\x1b[0m`,
};

function envFile() {
  return join(homedir(), '.config', 'bizar', 'cubesandbox.env');
}

function loadEnv() {
  const p = envFile();
  if (!existsSync(p)) return {};
  const out = {};
  for (const line of readFileSync(p, 'utf8').split('\n')) {
    const m = /^([A-Z_][A-Z0-9_]*)=(.*)$/.exec(line.trim());
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function writeEnv(env) {
  const p = envFile();
  const text = [
    `# Generated by bizar sandbox install — do not edit by hand.`,
    `CUBESANDBOX_API_KEY=${env.CUBESANDBOX_API_KEY || ''}`,
    `CUBESANDBOX_URL=${env.CUBESANDBOX_URL || 'http://127.0.0.1:12088'}`,
    `CUBESANDBOX_TEMPLATE=${env.CUBESANDBOX_TEMPLATE || 'base'}`,
    '',
  ].join('\n');
  writeFileSync(p, text, { mode: 0o600 });
}

function pythonAvailable() {
  const r = spawnSync('python', ['-c', 'import cubesandbox; print(cubesandbox.__version__)'], { stdio: 'pipe' });
  return r.status === 0;
}

async function cmdDoctor() {
  console.log(COLOR.cyan('▶ bizar sandbox doctor'));
  const env = loadEnv();
  const url = env.CUBESANDBOX_URL || 'http://127.0.0.1:12088';
  const key = env.CUBESANDBOX_API_KEY || '';
  console.log(`  url: ${url || '(unset)'}`);
  console.log(`  api key: ${key ? '****' + key.slice(-4) : COLOR.red('(unset)')}`);
  console.log(`  python SDK: ${pythonAvailable() ? COLOR.green('installed') : COLOR.yellow('missing — `pip install cubesandbox`')}`);

  if (url) {
    try {
      const r = await fetch(`${url.replace(/\/$/, '')}/health`);
      console.log(`  ${url}/health: ${r.status === 200 ? COLOR.green(`${r.status} OK`) : COLOR.yellow(`${r.status}`)}`);
    } catch (err) {
      console.log(`  ${url}/health: ${COLOR.red('unreachable')} (${err.message})`);
      console.log(COLOR.yellow('  hint: CubeSandbox control node typically listens on :12088 of the host'));
    }
  }
}

async function cmdRun({ lang, script, args }) {
  if (!lang || !script) {
    console.error(COLOR.red('usage: bizar sandbox run <bash|python|node> <script> [-- args...]'));
    process.exit(2);
  }
  const env = loadEnv();
  const template = env.CUBESANDBOX_TEMPLATE || 'base';
  const apiKey = env.CUBESANDBOX_API_KEY;
  const url = env.CUBESANDBOX_URL || 'http://127.0.0.1:12088';
  if (!apiKey) {
    console.error(COLOR.red('CUBESANDBOX_API_KEY missing — run `bizar sandbox doctor` first'));
    process.exit(1);
  }
  const pythonScript = `
from cubesandbox import Sandbox
import sys, json

with Sandbox(template="${template}", api_key="${apiKey}", domain="${url}") as box:
    r = box.run(${JSON.stringify(script)})
    json.dump({
      "sandbox_id": box.sandbox_id,
      "stdout": r.stdout,
      "stderr": r.stderr,
      "exit_code": r.exit_code,
    }, sys.stdout)
`;
  const r = spawnSync('python', ['-c', pythonScript], { stdio: 'inherit' });
  process.exit(r.status ?? 1);
}

async function cmdInstallTemplate({ name }) {
  if (!name) {
    console.error(COLOR.red('usage: bizar sandbox install-template <name>'));
    process.exit(2);
  }
  const pythonScript = `
from cubesandbox import Sandbox
sb = Sandbox.create(template="${name}")
sb.wait_for_ready(timeout=120)
print(f"template {sb.template_name} installed: {sb.sandbox_id}")
sb.kill()
`;
  const r = spawnSync('python', ['-c', pythonScript], { stdio: 'inherit' });
  process.exit(r.status ?? 1);
}

async function cmdList() {
  const env = loadEnv();
  if (!env.CUBESANDBOX_API_KEY) {
    console.error(COLOR.red('CUBESANDBOX_API_KEY missing — run `bizar sandbox doctor` first'));
    process.exit(1);
  }
  const pythonScript = `
from cubesandbox import Sandbox
import json
print(json.dumps(Sandbox.list(), indent=2, default=str))
`;
  const r = spawnSync('python', ['-c', pythonScript], { stdio: 'inherit' });
  process.exit(r.status ?? 1);
}

async function cmdKill({ id }) {
  if (!id) {
    console.error(COLOR.red('usage: bizar sandbox kill <sandbox-id>'));
    process.exit(2);
  }
  const r = spawnSync('python', ['-c', `
from cubesandbox import Sandbox
Sandbox.kill("${id}")
print("killed", "${id}")
`], { stdio: 'inherit' });
  process.exit(r.status ?? 1);
}

function printHelp() {
  console.log(`bizar sandbox — CubeSandbox (E2B-compatible) integration

Usage:
  bizar sandbox doctor                   Check SDK + control-node reachability
  bizar sandbox run <lang> <script>      Run a script in a fresh sandbox
  bizar sandbox install-template <name>  Install a template from Template Store
  bizar sandbox list                     List active sandboxes
  bizar sandbox kill <id>                Kill a running sandbox
  bizar sandbox config                   Write ~/.config/bizar/cubesandbox.env

Environment (set with \`bizar sandbox config\`):
  CUBESANDBOX_URL       control-node URL (default http://127.0.0.1:12088)
  CUBESANDBOX_API_KEY   API key from the WebUI
  CUBESANDBOX_TEMPLATE  default template (default "base")
`);
}

async function cmdConfig(args) {
  const env = loadEnv();
  if (args.url) env.CUBESANDBOX_URL = args.url;
  if (args.key) env.CUBESANDBOX_API_KEY = args.key;
  if (args.template) env.CUBESANDBOX_TEMPLATE = args.template;
  writeEnv(env);
  console.log(COLOR.green(`✓ wrote ${envFile()}`));
}

function parseArgs(argv) {
  const out = { _: [] };
  for (let i = 0; i < argv.length; i++) {
    const a = argv[i];
    if (a.startsWith('--')) {
      const eq = a.indexOf('=');
      if (eq >= 0) out[a.slice(2, eq)] = a.slice(eq + 1);
      else out[a.slice(2)] = argv[++i] ?? 'true';
    } else {
      out._.push(a);
    }
  }
  return out;
}

export async function runSandbox(argv) {
  const args = parseArgs(argv);
  const sub = args._[0];
  switch (sub) {
    case 'doctor': return cmdDoctor();
    case 'run':     return cmdRun({ lang: args._[1], script: args._[2], args });
    case 'list':    return cmdList();
    case 'kill':    return cmdKill({ id: args._[1] });
    case 'install-template': return cmdInstallTemplate({ name: args._[1] });
    case 'config':  return cmdConfig(args);
    case 'help':
    case '--help':
    case '-h':
    case undefined:
      printHelp();
      return;
    default:
      console.error(COLOR.red(`unknown subcommand: ${sub}`));
      printHelp();
      process.exit(2);
  }
}
