/**
 * CubeSandbox/E2B-compatible isolated code execution.
 *
 * Current CubeSandbox releases expose the E2B Code Interpreter contract:
 * E2B_API_URL, E2B_API_KEY, CUBE_TEMPLATE_ID, and Sandbox.create().
 */
import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';

export function envFile() {
  return join(homedir(), '.config', 'bizar', 'cubesandbox.env');
}

export function loadSandboxEnv(path = envFile()) {
  if (!existsSync(path)) return {};
  return Object.fromEntries(readFileSync(path, 'utf8').split('\n').map((line) => {
    const match = /^([A-Z_][A-Z0-9_]*)=(.*)$/.exec(line.trim());
    return match ? [match[1], match[2]] : null;
  }).filter(Boolean));
}

export function writeSandboxEnv(values, path = envFile()) {
  mkdirSync(dirname(path), { recursive: true });
  const text = [
    '# Generated by bizar sandbox config',
    `E2B_API_URL=${values.E2B_API_URL || 'http://127.0.0.1:3000'}`,
    `E2B_API_KEY=${values.E2B_API_KEY || ''}`,
    `CUBE_TEMPLATE_ID=${values.CUBE_TEMPLATE_ID || ''}`,
    '',
  ].join('\n');
  writeFileSync(path, text, { mode: 0o600 });
  return path;
}

const PYTHON_RUNNER = String.raw`
import json, sys
from e2b_code_interpreter import Sandbox

request = json.load(sys.stdin)
with Sandbox.create(template=request["template"]) as sandbox:
    execution = sandbox.run_code(request["code"], language=request["language"])
    json.dump({
        "sandbox_id": getattr(sandbox, "sandbox_id", None),
        "stdout": [getattr(item, "line", str(item)) for item in execution.logs.stdout],
        "stderr": [getattr(item, "line", str(item)) for item in execution.logs.stderr],
        "errors": [str(execution.error)] if execution.error else [],
        "text": getattr(execution, "text", None),
    }, sys.stdout)
`;

export function buildSandboxRequest(language, code, env) {
  if (!['python', 'javascript', 'typescript', 'r', 'java', 'bash'].includes(language)) {
    throw new Error(`unsupported language: ${language}`);
  }
  if (!code) throw new Error('code is required');
  if (!env.CUBE_TEMPLATE_ID) throw new Error('CUBE_TEMPLATE_ID is required');
  return { language, code, template: env.CUBE_TEMPLATE_ID };
}

function parseArgs(argv) {
  const values = { _: [] };
  for (let index = 0; index < argv.length; index++) {
    const value = argv[index];
    if (value.startsWith('--')) values[value.slice(2)] = argv[++index] ?? '';
    else values._.push(value);
  }
  return values;
}

function help() {
  console.log(`bizar sandbox — CubeSandbox isolated execution

Usage:
  bizar sandbox doctor
  bizar sandbox config --url <url> --key <key> --template <id>
  bizar sandbox run <python|javascript|typescript|r|java|bash> <code>

Requires Python package e2b-code-interpreter and a CubeSandbox control plane.`);
}

export async function runSandbox(argv = []) {
  const args = parseArgs(argv);
  const command = args._[0];
  const path = envFile();
  const saved = loadSandboxEnv(path);

  if (!command || command === 'help') {
    help();
    return { ok: true };
  }
  if (command === 'config') {
    const next = {
      E2B_API_URL: args.url || saved.E2B_API_URL,
      E2B_API_KEY: args.key || saved.E2B_API_KEY,
      CUBE_TEMPLATE_ID: args.template || saved.CUBE_TEMPLATE_ID,
    };
    writeSandboxEnv(next, path);
    console.log(`✓ wrote ${path}`);
    return { ok: true, path };
  }

  const python = spawnSync('python3', ['-c', 'import e2b_code_interpreter'], { stdio: 'ignore' });
  if (command === 'doctor') {
    const ready = python.status === 0 && !!saved.E2B_API_URL && !!saved.E2B_API_KEY && !!saved.CUBE_TEMPLATE_ID;
    console.log(`SDK: ${python.status === 0 ? 'ready' : 'missing (pip install e2b-code-interpreter)'}`);
    console.log(`URL: ${saved.E2B_API_URL || '(unset)'}`);
    console.log(`API key: ${saved.E2B_API_KEY ? `****${saved.E2B_API_KEY.slice(-4)}` : '(unset)'}`);
    console.log(`Template: ${saved.CUBE_TEMPLATE_ID || '(unset)'}`);
    return { ok: ready };
  }
  if (command !== 'run') throw new Error(`unknown sandbox subcommand: ${command}`);
  if (python.status !== 0) throw new Error('e2b-code-interpreter is not installed');

  const request = buildSandboxRequest(args._[1], args._[2], saved);
  const result = spawnSync('python3', ['-c', PYTHON_RUNNER], {
    input: JSON.stringify(request),
    encoding: 'utf8',
    timeout: 10 * 60_000,
    env: { ...process.env, ...saved },
  });
  if (result.status !== 0) throw new Error((result.stderr || `sandbox exited ${result.status}`).trim());
  process.stdout.write(result.stdout);
  return { ok: true, output: result.stdout };
}
