/**
 * plugins/bizar/tests/loop-engineering.test.ts
 *
 * Unit tests for the loop-engineering module + loop tools. Covers:
 *   - startLoop / loadLoop / saveLoop roundtrip
 *   - appendIteration updates status when stop condition met
 *   - listLoops filter
 *   - deleteLoop removes from disk
 *   - buildNextIteration for ralph, cron, plan-execute patterns
 */
import { describe, test, expect, beforeEach, afterEach } from "bun:test";
import { mkdtempSync, rmSync, readdirSync, existsSync } from "node:fs";
import { join } from "node:path";
import { tmpdir } from "node:os";

import {
  startLoop,
  loadLoop,
  saveLoop,
  appendIteration,
  stopLoop,
  deleteLoop,
  listLoops,
  buildNextIteration,
} from "../src/loop-engineering.js";

// Override the LOOPS_DIR via mocking would be ideal, but we just use
// the default ~/.bizar/loops and clean up after ourselves. Each test
// uses a unique loop id (generated by startLoop) so there's no collision.

describe("loop-engineering — basic CRUD", () => {
  const createdIds: string[] = [];

  afterEach(() => {
    for (const id of createdIds) {
      deleteLoop(id);
    }
    createdIds.length = 0;
  });

  test("startLoop creates a loop on disk with status=running", () => {
    const { ok, loop } = startLoop({ pattern: "ralph", task: "test task" });
    expect(ok).toBe(true);
    expect(loop.id).toMatch(/^loop_/);
    expect(loop.pattern).toBe("ralph");
    expect(loop.task).toBe("test task");
    expect(loop.status).toBe("running");
    expect(loop.iterations).toEqual([]);
    expect(loop.context.maxIterations).toBe(10);
    createdIds.push(loop.id);

    // Should be loadable.
    const loaded = loadLoop(loop.id);
    expect(loaded).not.toBeNull();
    expect(loaded!.id).toBe(loop.id);
  });

  test("appendIteration adds iteration and respects stop marker (ralph)", () => {
    const { loop } = startLoop({
      pattern: "ralph",
      task: "test ralph",
      context: { maxIterations: 10, stopMarker: "[STOP]" },
    });
    createdIds.push(loop.id);

    appendIteration(loop.id, {
      durationMs: 100,
      output: "working on it",
    });
    let updated = loadLoop(loop.id)!;
    expect(updated.iterations).toHaveLength(1);
    expect(updated.status).toBe("running");

    appendIteration(loop.id, {
      durationMs: 50,
      output: "done [STOP]",
    });
    updated = loadLoop(loop.id)!;
    expect(updated.iterations).toHaveLength(2);
    expect(updated.status).toBe("done");
    expect(updated.iterations[1].stopReason).toContain("[STOP]");
  });

  test("appendIteration hits maxIterations and sets status=done", () => {
    const { loop } = startLoop({
      pattern: "cron",
      task: "test cron",
      context: { maxIterations: 3 },
    });
    createdIds.push(loop.id);

    for (let i = 0; i < 3; i++) {
      appendIteration(loop.id, { durationMs: 10, output: `iter ${i}` });
    }
    const updated = loadLoop(loop.id)!;
    expect(updated.iterations).toHaveLength(3);
    expect(updated.status).toBe("done");
  });

  test("stopLoop marks as stopped with reason", () => {
    const { loop } = startLoop({ pattern: "repl", task: "interactive" });
    createdIds.push(loop.id);
    const stopped = stopLoop(loop.id, "user request");
    expect(stopped).not.toBeNull();
    expect(stopped!.status).toBe("stopped");
    expect(stopped!.iterations[0].stopReason).toBe("user request");
  });

  test("listLoops returns only matching loops", () => {
    const a = startLoop({ pattern: "ralph", task: "A" });
    const b = startLoop({ pattern: "cron", task: "B" });
    const c = startLoop({ pattern: "ralph", task: "C" });
    createdIds.push(a.loop.id, b.loop.id, c.loop.id);

    const all = listLoops();
    const ralphs = listLoops({ pattern: "ralph" });
    const stopped = listLoops({ status: "running" });

    expect(all.length).toBeGreaterThanOrEqual(3);
    expect(ralphs.length).toBeGreaterThanOrEqual(2);
    expect(ralphs.some((l) => l.id === a.loop.id)).toBe(true);
    expect(ralphs.some((l) => l.id === c.loop.id)).toBe(true);
    expect(stopped.length).toBeGreaterThanOrEqual(3);

    stopLoop(b.loop.id);
    const stoppedAfter = listLoops({ status: "stopped" });
    expect(stoppedAfter.some((l) => l.id === b.loop.id)).toBe(true);
  });

  test("deleteLoop removes from disk", () => {
    const { loop } = startLoop({ pattern: "ralph", task: "to-delete" });
    expect(loadLoop(loop.id)).not.toBeNull();
    expect(deleteLoop(loop.id)).toBe(true);
    expect(loadLoop(loop.id)).toBeNull();
  });
});

describe("buildNextIteration — pattern prompts", () => {
  test("ralph prompt includes task and stop marker", () => {
    const { loop } = startLoop({
      pattern: "ralph",
      task: "iterate me",
      context: { maxIterations: 5, stopMarker: "[DONE]" },
    });
    const next = buildNextIteration(loop);
    expect(next.stopMarker).toBe("[DONE]");
    expect(next.prompt).toContain("iterate me");
    expect(next.prompt).toContain("[DONE]");
  });

  test("cron prompt is just the task", () => {
    const { loop } = startLoop({ pattern: "cron", task: "do cron thing" });
    const next = buildNextIteration(loop);
    expect(next.prompt).toBe("do cron thing");
    expect(next.stopMarker).toBeNull();
  });

  test("plan-execute prompt uses subtasks array index", () => {
    const { loop } = startLoop({
      pattern: "plan-execute",
      task: "plan",
      context: { subtasks: ["step 1", "step 2", "step 3"] },
    });
    expect(buildNextIteration(loop).prompt).toContain("step 1");
    appendIteration(loop.id, { durationMs: 1, output: "ok" });
    expect(buildNextIteration(loadLoop(loop.id)!).prompt).toContain("step 2");
  });
});